select
LOCATION,
max(TOTAL_CASES_PER_MILLION) TOTAL_CASES_PER_MILLION,
max(TOTAL_RECOVERED) TOTAL_RECOVERED,
max(TOTAL_ACTIVE_CASES) TOTAL_ACTIVE_CASES,
max(TOTAL_DEATHS) TOTAL_DEATHS,
max(TOTAL_DEATHS_PER_MILLION) TOTAL_DEATHS_PER_MILLION,
max(TOTAL_CASES) TOTAL_CASES
from
{{ source('GOOGLE_SHEETS', 'COVID_19_INDONESIA_NITISH_POIGAL') }}
group by LOCATION